/**
 * schema-loader.mjs
 *
 * Parses plugin/skills/generate-hp-wp-page/references/acf-schemas.md into a
 * structured map keyed by Gutenberg block name (without the `acf/` prefix).
 *
 * The reference file is auto-generated by sync-acf-context.js; do not edit it
 * manually. This loader only reads.
 *
 * Each module entry:
 *   {
 *     blockName: "accordion",            // matches `acf/<blockName>` in markup
 *     fields: [
 *       { name, key, type, choices?, default? },
 *       ...
 *     ],
 *     repeaters: {
 *       accordion_repeater: {
 *         key: "field_...",
 *         subFields: [{ name, key, type }, ...]
 *       }
 *     }
 *   }
 *
 * Unnamed schema entries with type `tab` or `accordion` are UI grouping
 * markers in WP Admin — skipped here because they never appear in block JSON.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

export const DEFAULT_SCHEMA_PATH = join(
    __dirname,
    '..',
    'skills',
    'generate-hp-wp-page',
    'references',
    'acf-schemas.md',
);

const MODULE_HEADER_RE = /^## Module: (.+)$/;
const BLOCK_NAME_RE = /^\*\*Gutenberg Block Name:\*\* `acf\/([a-z0-9_-]+)`/;
const FIELD_LINE_RE = /^(\s*)- \*\*([^*]*)\*\* \(`([^`]+)`\) -> Key: `([^`]+)`(.*)$/;
const CHOICES_RE = /-> Choices: (.+?)(?: -> Default:|$)/;
const DEFAULT_RE = /-> Default: `([^`]*)`/;

const UI_TYPES = new Set(['tab', 'accordion', 'group']);

function parseChoices(tail) {
    const m = tail.match(CHOICES_RE);
    if (!m) return undefined;
    return m[1].split('|').map(s => s.trim().replace(/^`|`$/g, '')).filter(Boolean);
}

function parseDefault(tail) {
    const m = tail.match(DEFAULT_RE);
    return m ? m[1] : undefined;
}

export function loadSchemas(path = DEFAULT_SCHEMA_PATH) {
    const raw = readFileSync(path, 'utf8');
    const lines = raw.split(/\r?\n/);
    const modules = new Map();

    let current = null;
    let currentRepeater = null;

    for (const line of lines) {
        const moduleHeader = line.match(MODULE_HEADER_RE);
        if (moduleHeader) {
            current = { title: moduleHeader[1].trim(), blockName: null, fields: [], repeaters: {} };
            currentRepeater = null;
            continue;
        }

        if (!current) continue;

        const blockName = line.match(BLOCK_NAME_RE);
        if (blockName) {
            current.blockName = blockName[1];
            modules.set(current.blockName, current);
            continue;
        }

        if (line.startsWith('---') || line.startsWith('## ')) {
            current = null;
            currentRepeater = null;
            continue;
        }

        const field = line.match(FIELD_LINE_RE);
        if (!field || !current.blockName) continue;

        const [, indent, name, type, key, tail] = field;
        const isNested = indent.length >= 2;

        if (UI_TYPES.has(type) && !name) {
            if (!isNested) currentRepeater = null;
            continue;
        }

        const fieldDef = {
            name,
            key,
            type,
            choices: parseChoices(tail),
            default: parseDefault(tail),
        };

        if (!isNested) {
            current.fields.push(fieldDef);
            if (type === 'repeater') {
                currentRepeater = { key, subFields: [] };
                current.repeaters[name] = currentRepeater;
            } else {
                currentRepeater = null;
            }
        } else if (currentRepeater) {
            if (!name) continue;
            currentRepeater.subFields.push(fieldDef);
        }
    }

    return modules;
}
